mybatis:
  type-aliases-package: com.vidi.demo.model
  config-location: classpath:config/mybatis-config.xml
  mapper-locations: classpath:mapper/*.xml
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/mybatis_original?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: 294127003
server:
  port: 9090
logging:
  level:
    com.vidi.demo.mybatis.dao: debug





